version: '3.8'

services:
  blockchain:
    build: ./
    command: ./wait-for-postgres.sh db ./blockchain
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: -p ${DB_PORT}
